version: '3.0'
services:
  sejutacitatest-app:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 5000:5000
    environment:
      - MONGODB_DOCKER_HOST=sejutacitatest-mongo
    links:
      - sejutacitatest-mongo
  sejutacitatest-mongo:
    image: mongo:latest
    volumes:
      - /mongodb:/data/db
    ports:
      - 27018:27017
  