apiVersion: apps/v1
kind: Deployment
metadata:
  name: sejutacitatest
spec:
  selector:
    matchLabels:
      app: sejutacitatest
  replicas: 3
  template:
    metadata:
      labels:
        app: sejutacitatest
    spec:
      containers:
      - name: sejutacitatest
        image: sejutacitatest_sejutacitatest-app
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
      - name: sejutacitatest-mongo
        image: mongo
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 27018
        volumeMounts:
          - name : mongo-volume
            mountPath: /data/db
      volumes:
        - name: "mongo-volume"
          hostPath:
            path: /mnt/data/mongodb
       

--- 

apiVersion: v1
kind: Service
metadata:
  name: sejutacitatest
spec:
  selector:
    app: sejutacitatest
  ports:
    - protocol: "TCP"
      port: 5000
      targetPort: 5000
  type: NodePort

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: sejutacitatest-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data"


---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sejutacitatest-pv-claim
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi